[package]
name = "thistle"
version = "0.1.0"
authors = ["Brad Windsor <bwindsor22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
uuid = { version = "0.7", features = ["serde", "v4"] }
sbert = "0.3.0"